package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Age    int         `json:"age"`
	Name   string      `json:"name"`
	Child  []int       `json:"child"`
	ChildM map[int]int `json:"child_m"`
}

func main() {
	//tmp:=AutoGenerated{}
	//tmp.ChildM= map[int]int{1:2}
	//fmt.Println(jsoniter.MarshalToString(tmp))
	jsonStr1 := `{"age": 14,"name": "potter", "child":[1,2,3] ,"child_m":{"1":2}}`
	a := AutoGenerated{}
	json.Unmarshal([]byte(jsonStr1), &a)
	aa := a.Child
	bb := a.ChildM
	fmt.Println(aa)
	fmt.Println(bb)
	jsonStr2 := `{"age": 12,"name": "potter", "child":[3,4,5,7,8,9],"child_m":{"2":3}}`
	json.Unmarshal([]byte(jsonStr2), &a)
	fmt.Println(aa)
	fmt.Println(bb)
}
