// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"fmt"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAllInstance() *Instance {
	foo := NewFoo()
	bar := NewBar(foo)
	instance := &Instance{
		Foo: foo,
		Bar: bar,
	}
	return instance
}

// wire.go:

type Foo struct {
}

func NewFoo() *Foo {
	return &Foo{}
}

type Bar struct {
	foo *Foo
}

func NewBar(foo *Foo) *Bar {
	return &Bar{
		foo: foo,
	}
}

func (p *Bar) Test() {
	fmt.Println("hello")
}

type Instance struct {
	Foo *Foo
	Bar *Bar
}

var SuperSet = wire.NewSet(NewFoo, NewBar)
